# Build hets and run related tests for CI
name: CI-Test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request cwfor the given branches
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

# A workflow run is made up of one or more jobs that can run seq. or in parallel
jobs:
  version:
    # TBD: ubuntu-20.04 or macos-11
    runs-on: ubuntu-18.04
    steps:
      # checkout the hets repo
      #- uses: actions/checkout@v2
      # execute the follwoing commands:
      - run: |
          set
          echo '###########################################################'
          grep '^model name' /proc/cpuinfo
          egrep '^(Mem|Swap)' /proc/meminfo
          echo '###########################################################'

