# Build hets and run related tests for CI
name: CI-Test

env:
  SKIP_STACK: 0
  SKIP_BUILD: 0
  SKIP_TEST: 0
  SKIP_HADDOCK: 0
  PKG_CACHE: /var/tmp/pkgs
  SMART_CACHE: 1
  NO_DOCS: 1
  #MKDBG: 1
  # GHA vare settings totally sucks: impossible to use already defined vars =8-(
  STACK_ROOT: /var/tmp/stack
  HETS_BASEDIR: /var/tmp/hets
  HETS_BUILD_DIR: ${HETS_BASEDIR}/build
  PREFIX: /tmp/hets-install
  #PATH: ${PREFIX}/bin:${STACK_ROOT}/bin:${PATH}
  HETS_LIB: /var/tmp/Hets-lib
  HETS_MAGIC: ${TRAVIS_BUILD_DIR}/magic/hets.magic
  TH: utils/travis-helper.sh

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request cwfor the given branches
  push:
    branches:
      - gha
  pull_request:
    branches:
      - gha

# A workflow run is made up of one or more jobs that can run seq. or in parallel
jobs:
  job_1:
    name: Show environment
    # TBD: ubuntu-20.04 or macos-11
    runs-on: ubuntu-18.04
    steps:
      # execute the follwoing commands:
      - name: Environment
        run: |
          eval HETS_MAGIC=${HETS_MAGIC}
          set
          echo '###########################################################'
          grep '^model name' /proc/cpuinfo
          egrep '^(Mem|Swap)' /proc/meminfo
          echo '###########################################################'
          uname -a
          ip a
          networkctl
          networkctl status
  job_2:
    name: Stack
    runs-on: ubuntu-18.04
    needs: job_1
      # build stack
      # ${{github.workspace}}/build  ${{env.BUILD_TYPE}}
      # CI=true                   RUNNER_WORKSPACE=/home/runner/work/$REPO
      # GITHUB_WORKFLOW=CI-Test   GITHUB_WORKSPACE=${RUNNER_WORKSPACE}/$REPO
      # GITHUB_EVENT_NAME=push    GITHUB_REPOSITORY=jelmd/$REPO
      # GITHUB_REF_TYPE=branch    GITHUB_REF=refs/heads/$BRANCH
      # LANG=C.UTF-8
    steps:
      # checkout the hets repo
      - uses: actions/checkout@v2
      - name: Environment
        run: |
          networkctl
          networkctl status
          grep '^model name' /proc/cpuinfo
          egrep '^(Mem|Swap)' /proc/meminfo
          set | grep ^GITHUB_
          echo '###########################################################'
          # crazy: /var/tmp/ is per default not writable
          sudo chmod 01777 /var/tmp
          ls -al /var/tmp/
          pwd
          echo GITHUB_WORKSPACE=${GITHUB_WORKSPACE}
          echo STACK_ROOT=${STACK_ROOT}
      - name: Stack
          cd ${GITHUB_WORKSPACE}
          pwd
          make stack
          ls -alR
          ls -alR ${STACK_ROOT} 
