# Build hets and run related tests for CI
name: CI-Test

env:
  SKIP_STACK: 0
  SKIP_BUILD: 0
  SKIP_TEST: 0
  SKIP_HADDOCK: 0
  #PKG_CACHE: /var/tmp/pkgs
  SMART_CACHE: 1
  NO_DOCS: 1
  #MKDBG: 1
  # GHA var settings totally sucks: impossible to use already defined vars =8-(
  STACK_ROOT: /var/tmp/stack
  GAH: utils/gha-helper.sh
  #HETS_BASEDIR: /var/tmp/hets
  #HETS_BUILD_DIR: ${HETS_BASEDIR}/build
  #PREFIX: /tmp/hets-install
  #PATH: ${PREFIX}/bin:${STACK_ROOT}/bin:${PATH}
  #HETS_LIB: /var/tmp/Hets-lib
  #HETS_MAGIC: ${TRAVIS_BUILD_DIR}/magic/hets.magic

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request cwfor the given branches
  push:
    branches:
      - gha
  pull_request:
    branches:
      - gha

# A workflow run is made up of one or more jobs that can run seq. or in parallel
# but always in a separate, fresh container. So each job needs to fetch the work
# from previous jobs and checkout the repo again, if needed.
#
# Re-usable workflows? Forget this non-sense. Write a script and put it in there
# than you have re-usable stuff which can be run on any step, several times ...
jobs:
  job_1:
    name: Stack
    runs-on: ubuntu-18.04
    steps:
      - name: Update packages
        run: |
          printf 'man-db man-db/auto-update boolean false\n' | sudo debconf-set-selections
          sudo apt-get install ksh93 || sudo apt-get install ksh
          sudo apt-get install libpango1.0-dev libgtk2.0-dev

      - name: Checkout
        uses: actions/checkout@v2

      - name: Download stack
        continue-on-error: true
        uses: actions/download-artifact@v2
        with:
          name: ${{ github.repository }}-stack.tgz
          path: ${{ env.STACK_ROOT }}/${{ github.repository }}

      - name: Build stack
        run: |
          ${{ env.GAH }} -c showEnv
          ${{ env.GAH }} -c makeStackx

      - name: Upload stack
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.repository }}-stack.tgz
          path: ${{ env.STACK_ROOT }}.tgz
          if-no-files-found: error
          # rebuild once a month
          retention-days: 30

